name: Build Packages

on:
  workflow_dispatch:
  pull_request:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      NIXPKGS_ALLOW_UNFREE: 1
      NIXPKGS_ALLOW_INSECURE: 1
    steps:
    - uses: actions/checkout@v4

    - uses: cachix/install-nix-action@v26
      with:
        nix_path: nixpkgs=channel:nixos-unstable
        extra_nix_config: experimental-features = nix-command flakes

    - uses: DeterminateSystems/magic-nix-cache-action@v6
      with:
        use-flakehub: false

    - uses: cachix/cachix-action@v14
      with:
        name: abszero
        authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}

    - name: Build package
      run: nix flake check --impure ./pkgs
