name: Build

on:
  workflow_dispatch:
  pull_request:
  push:

jobs:
  get-packages:
    runs-on: ubuntu-latest
    outputs:
      packages: ${{ steps.get-packages.outputs.packages }}
    steps:
    - uses: actions/checkout@v4

    - uses: cachix/install-nix-action@v26
      with:
        nix_path: nixpkgs=channel:nixos-unstable

    - name: Get packages
      id: get-packages
      shell: bash # Set pipefail
      run: echo "packages=$(nix flake show --json | jq -c '.packages."x86_64-linux" | keys')" >> "$GITHUB_OUTPUT"

  build:
    runs-on: ubuntu-latest
    needs: get-packages
    strategy:
      fail-fast: false
      matrix:
        package: ${{ fromJson(needs.get-packages.outputs.packages) }}
    env:
      NIXPKGS_ALLOW_UNFREE: 1
      NIXPKGS_ALLOW_BROKEN: 1
      NIXPKGS_ALLOW_INSECURE: 1
    steps:
    - uses: actions/checkout@v4

    - uses: cachix/install-nix-action@v26
      with:
        nix_path: nixpkgs=channel:nixos-unstable
        extra_nix_config: experimental-features = nix-command flakes

    - uses: DeterminateSystems/magic-nix-cache-action@v3

    - uses: cachix/cachix-action@v14
      with:
        name: abszero
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'

    - name: Build package
      run: nix build --impure .#${{ matrix.package }}
