name: Automatic Hash Update

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */3 * * *"

jobs:
  get-update-scripts:
    runs-on: ubuntu-latest
    outputs:
      update-scripts: ${{ steps.get-update-scripts.outputs.update-scripts }}
    steps:
      - uses: actions/checkout@v4

      - name: Get update scripts
        id: get-update-scripts
        run: echo "update-scripts=$(find . -name "update.sh" | jq -cnR '[inputs]')" >> "$GITHUB_OUTPUT"

  update:
    runs-on: ubuntu-latest
    needs: get-update-scripts
    strategy:
      matrix:
        update-script: ${{ fromJson(needs.get-update-scripts.outputs.update-scripts) }}
    steps:
      - uses: actions/checkout@v4

      - uses: cachix/install-nix-action@v23
        with:
          nix_path: nixpkgs=channel:nixos-unstable
          extra_nix_config: |-
            experimental-features = nix-command flakes

      - name: Run update script
        id: update
        run: |-
          ${{ matrix.update-script }}
          # Escape newlines because YAML doesn't like multiline strings
          echo "diff=$(git diff | sed 's,$,!!!\\n,g' | tr -d '\n')" >> "$GITHUB_OUTPUT"

      # Matrix jobs overwrite each other's output, this is a workaround using artifacts
      - if: steps.update.outputs.diff != ''
        uses: cloudposse/github-action-matrix-outputs-write@0.4.2
        with:
          matrix-step-name: update
          matrix-key: ${{ matrix.update-script }}
          outputs: |-
            diffs: |-
              ${{ steps.update.outputs.diff }}

  commit:
    if: always()
    runs-on: ubuntu-latest
    needs: update
    steps:
      - id: read
        uses: cloudposse/github-action-matrix-outputs-read@0.1.1
        with:
          matrix-step-name: update

      - if: fromJson(steps.read.outputs.result).diffs != null
        uses: actions/checkout@v4

      - name: Apply diffs
        if: fromJson(steps.read.outputs.result).diffs != null
        env:
          DIFFS: ${{ toJson(fromJson(steps.read.outputs.result).diffs) }}
        run: bash <(echo "$DIFFS" | jq '.[] | "echo \(@sh) | sed \'s,!!!\\n,\n,g\' | git apply"')

      - if: fromJson(steps.read.outputs.result).diff != null
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: |
            pkgs: autoupdate

            uwu
          commit_author: github-actions[bot] <github-actions[bot]@users.noreply.github.com>
