name: Automatic Hash Update

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */3 * * *"

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: cachix/install-nix-action@v23
        with:
          nix_path: nixpkgs=channel:nixos-unstable
          extra_nix_config: |
            experimental-features = nix-command flakes

      # - name: Run update scripts
        # run: for p in $(find . -name "update-*.sh"); do $p; done

      - name: Update vscode-insiders
        continue-on-error: true
        run: pkgs/applications/editors/vscode/update-vscode-insiders.sh

      - name: Update vscodium-insiders
        continue-on-error: true
        run: pkgs/applications/editors/vscode/update-vscodium-insiders.sh

      - name: Update v2ray-rules-dat
        continue-on-error: true
        run: pkgs/data/misc/v2ray-rules-dat/update.sh

      - name: Update colloid-gtk-theme-git
        continue-on-error: true
        run: pkgs/data/themes/colloid-gtk-theme/update.sh

      - name: Update catppuccin-discord
        continue-on-error: true
        run: pkgs/data/themes/catppuccin-discord/update.sh

      - name: Update firefox-vertical-tabs
        continue-on-error: true
        run: home/modules/themes/base/firefox-vertical-tabs/update.sh

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: |
            pkgs: autoupdate

            uwu
          commit_author: github-actions[bot] <github-actions[bot]@users.noreply.github.com>
